#!/bin/bash

set -e

[[ -z "${distribution}" ]] && { echo "distribution not set"; exit 1; }
[[ -z "${version}" ]] && { echo "version not set"; exit 1; }

root="`pwd`"
docker_role_dir="/root/ansible-role-arouteserver"
temp_file=$(mktemp)

cd tests

function title() {
	echo ""
	echo "$(tput bold)$1$(tput sgr0)"
}

function do_stop() {
	docker stop docker_test &>/dev/null || true
	docker rm -f docker_test &>/dev/null || true
}

function do_new() {
	do_stop

	title "Starting a new Docker container... "
	docker run \
		--name docker_test \
		--detach \
		--privileged \
		-v ${root}:${docker_role_dir}:ro \
		-w /root \
		${distribution}-${version}:ansible

	# Copy the local tests/clients.yml into /root/tmp,
	# so that it can be found at the path referenced by
	# arouteserver_clients_cfg_file and it can also be
	# modified by this script as needed.
	docker exec docker_test mkdir /root/tmp
	docker cp clients.yml docker_test:/root/tmp/
}

function test_changed() {
	cat ${temp_file} | \
		grep -q "changed=$1.*failed=0" \
		&& (echo "$2: pass") \
		|| (echo "$2: fail" && exit 1)
}

do_new

# Syntax check.
title "Testing syntax check..."
docker exec docker_test \
	env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i ${docker_role_dir}/tests/inventory --syntax-check ${docker_role_dir}/tests/test.yml

# Scenario 1
cmd="env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i ${docker_role_dir}/tests/inventory ${docker_role_dir}/tests/scenario1.yml"

title "Testing scenario 1: local general.yml and clients.yml..."

docker exec docker_test ${cmd}

# rs1 IPv4
title "Checking rs1 IPv4 config..."
docker exec docker_test \
	bash -c 'cat /root/arouteserver/rs1-bird4.cfg | grep -q "router id 192.0.2.1"' \
	|| (echo 'invalid rs1 IPv4 config file' && exit 1)
docker exec docker_test \
	bash -c 'cat /root/arouteserver/rs1-bird4.cfg | grep -q "193.0.0.0/21"' \
	|| (echo 'IPv4 control prefix not found in rs1 config' && exit 1)

# rs1 IPv6
title "Checking rs1 IPv6 config..."
docker exec docker_test \
	bash -c 'cat /root/arouteserver/rs1-bird6.cfg | grep -q "router id 192.0.2.1"' \
	|| (echo 'invalid rs1 IPv6 config file' && exit 1)
docker exec docker_test \
	bash -c 'cat /root/arouteserver/rs1-bird6.cfg | grep -q "2001:500:4::/48"' \
	|| (echo 'IPv6 control prefix not found in rs1 config' && exit 1)

# rs2
title "Checking rs2 IPv4 and IPv6 config..."
docker exec docker_test \
	bash -c 'cat /root/arouteserver/rs2-openbgpd.cfg | grep -q "router-id 192.0.2.2"' \
	|| (echo 'invalid rs2 IPv4 config file' && exit 1)
docker exec docker_test \
	bash -c 'cat /root/arouteserver/rs2-openbgpd.cfg | grep -q "193.0.0.0/21"' \
	|| (echo 'IPv4 control prefix not found in rs2 config' && exit 1)
docker exec docker_test \
	bash -c 'cat /root/arouteserver/rs2-openbgpd.cfg | grep -q "2001:500:4::/48"' \
	|| (echo 'IPv6 control prefix not found in rs2 config' && exit 1)

title "Testing scenario 1 idempotence..."
docker exec docker_test ${cmd} | tee ${temp_file}
# No changes expected.
test_changed 0 "Idempotence test"

title "Testing 'upgrade' tag..."
docker exec docker_test ${cmd} -t upgrade | tee ${temp_file}
# No changes expected.
test_changed 0 "No changes after 'upgrade' test"

title "Testing 'configure_policy' tag..."
docker exec docker_test ${cmd} -t configure_policy | tee ${temp_file}
# No changes expected.
test_changed 0 "No changes after 'configure_policy' test"

title "Testing 'configure_clients' tag..."
docker exec docker_test ${cmd} -t configure_clients | tee ${temp_file}
# No changes expected.
test_changed 0 "No changes after 'configure_clients' test"

title "Testing 'build_rs_config' tag..."
docker exec docker_test ${cmd} -t build_rs_config | tee ${temp_file}
# No changes expected.
test_changed 0 "No changes after 'build_rs_config' test"

title "Testing clients.yml changes: comment only..."
docker exec docker_test bash -c 'echo \# >> /root/tmp/clients.yml'
docker exec docker_test ${cmd} -t configure_clients | tee ${temp_file}
# No changes expected (comments are stripped out).
test_changed 0 "No changes expected when clients.yml changes: comment only"

title "Testing clients.yml changes: new peer..."
docker exec docker_test bash -c 'cat << EOF >> /root/tmp/clients.yml
  - asn: 64497
    ip:
    - "192.0.2.33"
    - "2001:db:1:1::33"
EOF'
docker exec docker_test ${cmd} -t configure_clients | tee ${temp_file}
# Changes expected: 3 changes, clients.yml file and 2 route servers
test_changed 3 "Changes expected when clients.yml changes: new peer"

do_new

# Scenario 2
cmd="env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i ${docker_role_dir}/tests/inventory ${docker_role_dir}/tests/scenario2.yml"

title "Testing scenario 2: general.yml via 'configure' command..."

docker exec docker_test ${cmd}

do_new

# Scenario 3
cmd="env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v -i ${docker_role_dir}/tests/inventory ${docker_role_dir}/tests/scenario3.yml"

title "Testing scenario 2: clients.yml via Euro-IX URL..."

docker exec docker_test ${cmd}

title "Stopping and removing Docker container..."
do_stop
